### ISSUE TITLE
Do not support ds918 dsm7.2-64570-3

### ISSUE THREAD

**Issue by yh317** [007revad/Synology_enable_Deduplication#41]
![Uploading IMG_20240105_132924.jpg…]()

**Comment by yh317** [comment]
![IMG_20240105_132924](https://github.com/007revad/Synology_enable_Deduplication/assets/132770632/fab5be97-40f5-469d-a527-c15ebbf840e5)

**Comment by 007revad** [comment]
I've changed that message to say what CPU package architecture the Synology has.

Unfortunately the Apollolake CPU in your DS918+ does not support btrfs data deduplication. I've updated the readme page because it incorrectly listed the DS918+ and DS1019+ as supported.
