### ISSUE TITLE
Auto update is trying to copy the wrong script syno_hdd_db.sh instead of syno_enable_dedupe

### ISSUE THREAD

**Issue by herbingk** [007revad/Synology_enable_Deduplication#44]
Auto update is trying to copy syno_hdd_db.sh instead of syno_enable_dedupe.sh. The related script code is

                            # Copy new script sh files to script location
                            if ! cp -p "/tmp/$script-$shorttag/syno_hdd_db.sh" "${scriptpath}/${scriptfile}";
                            then

Thanks for looking into it.

**Comment by 007revad** [comment]
I found that a few days ago and have fixed it but haven't uploaded the updated script to GitHub yet.

**Comment by 007revad** [comment]
Fixed in https://github.com/007revad/Synology_enable_Deduplication/releases/tag/v1.2.17

Thank you.
