### ISSUE TITLE
Unable to load DSM UI after latest release

### ISSUE THREAD

**Issue by bslatyer** [007revad/Synology_enable_Deduplication#52]
Hello,

After running the latest script version and rebooting a DS420+ and DS920+ (which have been running fine), the DSM UI does not come online afterwards.

Container Manager, SMB/AFP/NFS and SSH are running after it reboots.

It just displays the following error page from NGINX.

![CleanShot 2024-01-09 at 14 15 12](https://github.com/007revad/Synology_enable_Deduplication/assets/64551242/c60a0574-563d-4b38-bfc4-32bc63f57b33)

**Comment by bslatyer** [comment]
I forgot to mention that running the `--restore` command does not fix the issue.

**Comment by 007revad** [comment]
Did you leave the browser window/tab open when you rebooted? I found that I needed to open a new window or tab and open the DSM webui before it would load.

Did you schedule the script to run? If yes, is it scheduled to run at shut down or bootup?

Which version of the script do you have? I uploaded a new version 2 hours ago, v1.3.19

**Comment by bslatyer** [comment]
I left both DSMs open while they were rebooting.

I also tried a different machine - the same issue.

The scripts are manually run and have always been that way.

Downloaded and ran v1.3.19 about an hour or so after it was released.

**Comment by bslatyer** [comment]
I reinstalled DSM via SSH on both units and haven't had issues since 17:00 this afternoon.

**Comment by songokussm** [comment]
i just updated on a ds723+ with no issues.

**Comment by 007revad** [comment]
I installed an extra 4GB of memory in my DS720+, ran the script and rebooted and had no issues.
