### ISSUE TITLE
Option visible but doesn't seem to work

### ISSUE THREAD

**Issue by rubenvarela** [007revad/Synology_enable_Deduplication#78]
Trying to set this up, I see the option available when I go to,

    Storage Manager > Storage > Volume > ... > Configure Data Deduplication

I see both options, 'Automatic Deduplication' and 'Manual Deduplication'. 

---

Manual Deduplication reads, 

- Status: Ready 
- Last Run Time: -

Automatic Deduplication reads 'Disabled on xxxx'

---

Under Manual Deduplication, when I select 'Run Now', it shows a quick 'Loading', it then returns, and nothing seems to happen. It still says "Status: Ready".

---

Happy to dig into it, but I'm trying to find ways of debugging. So far, 

- I don't see anything on Log Center. 
- In `/var/log/systemd.log` when I click 'Run Now', it adds an entry, `systemd[1]: Started Synology Btrfs Deduplication Service.`
- In `/var/log/synobtrfsdedupe.log` I see, 

```
2024-07-20T11:05:44-04:00 **NASNAME** synobtrfsdedupe[14719]: Delete subvol 9d29145b-9079-1d4f-9675-558f91e7bbea from config and sample index
2024-07-20T11:05:44-04:00 **NASNAME** synobtrfsdedupe[14719]: dedupe/service/service_operation_worker.cpp:15 Exception (dedupe/index/sample_index.cpp:53): Sample index not found: /volume1/@dedupe
```

if I `sudo ls /volume1/@dedupe/` I do see content,

```
$ sudo ls @dedupe/
dedupe.conf  reset_list
```

No idea where to go from here.

**Comment by 007revad** [comment]
Which model Synology do you have?

What does the following command return?
```
sudo ls -s -h -l /volume1/@dedupe
```

**Comment by rubenvarela** [comment]
Hey @007revad thanks for taking a look!

- Model: DS1621+
- DSM: DSM 7.2.1-69057 Update 5
- Memory: 36 GB


Output of the command,

```shell
sudo ls -s -h -l /volume1/@dedupe
Password:
total 4.0K
4.0K -rw------- 1 root root 1.2K Jul 15 19:31 dedupe.conf
   0 -rw------- 1 root root    0 Jun  8 05:26 reset_list
```

**Comment by rubenvarela** [comment]
@007revad I tried more stuff but couldn't find a way to fix the state. 

What I ended up doing, 
-  renamed `/volume1/@dedupe` to `@dedupe.backup`
- restarted the NAS
- upon booting, `@dedupe` at this point wasn't created
- going to storage manager > volume > configure deduplication, was showing under automatic deduplication the previous disabled time. 
- Under manual, I was seeing the option for "Run Now"
- I selected the  "Run Now" option at this point and it's finally showing "Running (0.0%)" and the option for Stop. 

If I run the previous ls command, I now see more files under the folder, 

```bash
$ sudo ls -s -h -l /volume1/@dedupe
total 8.0K
4.0K -rw------- 1 root root 470 Jul 27 12:55 dedupe.conf
   0 -rw------- 1 root root   0 Jul 27 12:55 dup
   0 -rw------- 1 root root   0 Jul 27 12:55 reset_list
4.0K -rw------- 1 root root  32 Jul 27 12:55 sample
```

Not sure if you'd like more info on setup or the actual backed up files. If not, I'm happy to close this at this point.

**Comment by 007revad** [comment]
Thanks for the feedback.

So the solution would be: 
1. Rename or delete the volume's `@dedupe`
2. Reboot the NAS.

I had assumed I'd be able to provide you the missing file(s) to put in `/volume1/@dedupe` but after your previous reply I noticed I have a 1/volumeX@dedupe` folder for each volume that I've had dedupe enabled on. And the files in them are different sizes. Then I forgot to reply. Sorry.
```
# ls -s -h -l /volume1/@dedupe
total 65M
4.0K -rw------- 1 root root  676 Jul 23 18:29 dedupe.conf
 64M -rw------- 1 root root  64M Jul 23 18:29 dup
   0 -rw------- 1 root root 256M Jan 10  2024 hole.cow
   0 -rw------- 1 root root 256M Jan 10  2024 hole.nocow
   0 -rw------- 1 root root    0 Jul 23 18:30 reset_list
960K -rw------- 1 root root 957K Jul 23 18:29 sample

# ls -s -h -l /volume2/@dedupe
total 8.0K
4.0K -rw------- 1 root root  354 Jul 19 20:00 dedupe.conf
   0 -rw------- 1 root root    0 Jul 19 19:49 dup
   0 -rw------- 1 root root 256M Jul 19 20:00 hole.cow
   0 -rw------- 1 root root 256M Jul 19 20:00 hole.nocow
   0 -rw------- 1 root root    0 Jul 19 20:00 reset_list
4.0K -rw------- 1 root root   32 Jul 19 19:49 sample
```
