### ISSUE TITLE
Deduplication configuration nt shown in volume menu

### ISSUE THREAD

**Issue by WAdama** [007revad/Synology_enable_Deduplication#79]
Hi,

it seems, the script has set everything correct, but I get not the menu point shown:
![dedup](https://github.com/user-attachments/assets/2d2f8c97-f986-4bf1-bb95-e697f30cca1e)

Output from syno_enable_dedupe.sh -c:
`Synology_enable_Deduplication v1.4.28
DS420+ DSM 7.2.1-69057-5

StorageManager 1.0.0-0017

Using options: -c
Running from: /volume1/Work/Scripts/SH/syno_enable_dedupe.sh
WARNING Don't store this script on an NVMe volume!

NAS has 10 GB of memory.

Btrfs Data Deduplication is not enabled.

Tiny Btrfs Data Deduplication is enabled.

Checking non-Synology drive supported.
File is already edited.

Checking value in backup file.
Backup file is okay.
`
But I see in Volume global settings the entry for setting automatic deduplication, which of course says, that there is no deduplication activated for a volume.

**Comment by 007revad** [comment]
Did you close and re-open Storage Manager.

**Comment by WAdama** [comment]
Hi Dave,

I restarted the system before this. That would be enough, wouldn't it?

Have I misunderstood something here? I have a system with hard drives and ssd's as cache. Is this not supported then?

**Comment by 007revad** [comment]
Yes, as you restarted the NAS you do not need to close and re-open storage manager.

>  I have a system with hard drives and ssd's as cache. Is this not supported then?

I think yes.

One way to be sure would be to:
1. Remove the cache from the volume.
2. Reboot.
3. Check if deduplication is now available.

I could maybe allow running deduplication on a volume with a cache but I don't know if your data would be safe.

**Comment by WAdama** [comment]
Hi Dave,

will check this, may need some time.

I can't remember any hint from Synology that deduplication with cache is not possible.

**Comment by 007revad** [comment]
No need to do those 3 steps. I just confirmed the cache is NOT the problem.

I added a read-only SSD cache to a HDD volume and was able set deduplication.

Then I deleted the read-only cache and created a read/write cache and was able set deduplication.

Read/write cache: 
![image](https://github.com/user-attachments/assets/341bc8b7-608b-47ad-ab3f-826a7bd5d7f5)

Read only cache:
![image](https://github.com/user-attachments/assets/6032592d-630f-412e-ae32-b7440e01a608)

**Comment by 007revad** [comment]
Have you previously run https://github.com/007revad/Synology_HDD_db

**Comment by WAdama** [comment]
Hi Dave,

thought that was just optional, will try that...

Regards
Ingo

**Comment by WAdama** [comment]
Hi Dave,

just tested it again with Synology_HDD_db, but I'm afraid, that made no difference.

Still only this part:
![dedup2](https://github.com/user-attachments/assets/c1a89854-4e09-42e9-9547-70804b89c871)

**Comment by 007revad** [comment]
I just remembered it can take up to 10 minutes before the deduplication menu appears. Can you check if the menu is still missing.

Another thought is that my Synology NAS have either a NVMe volume or a SATA SSD volume. When you have time can you try: 
- Just the HDD volume and no SSD cache.
- The HDD volume and a SSD volume.

Make sure to check after 10 minutes.

**Comment by sheckandar** [comment]
I had the same issue.

We have our synology configured in a HA cluster and when I ran the script on one of them only, nothing showed up in the Storage Manager. However, after I ran the script on both devices and rebooted both one by one, the option showed up the Storage Manager.

**Comment by WAdama** [comment]
Hi Dave,

sorry for answering so late. Even waiting more than 10 minutes and several restarts does not do the trick.

I have to admit, this feature is not that important for me to reconfigure my working NAS so massive.

I had hoped for a simplier reason for this error.

By the way, this is usable on an already configured and used file system? Not that that's the problem.

**Comment by 007revad** [comment]
> By the way, this is usable on an already configured and used file system?

Yes. 

I just remembered that deduplication requires: 
1. Data deduplication is only supported on Btrfs volumes. (which you have).
2. Data deduplication can only run when the volume status is Healthy. (which yours is).
3. Data deduplication requires you to Enable usage detail analysis for the Btrfs volume.

If you don't have "Usage detail analysis" enabled:
1. Go to Storage Manager > Storage.
2. Click the upper-right  icon of the Btrfs volume you want to configure.
3. Select Settings.
4. Go to the Usage Details section and tick the Enable usage detail analysis checkbox.
5. Click Save to confirm.

**Comment by WAdama** [comment]
Hi Dave,

all three prerequisites are fulfilled, so yes, usage detail analysis is active..

The full configuration of my volume:
RAID5 (no SHR) with 4 hdd's
Btrfs
Read/write ssd cache

Regards
Ingo

**Comment by MaximumFish** [comment]
> Btrfs Data Deduplication is _not_ enabled

A stupid question maybe, but are you definitely running the script with the `--hdd` option?

**Comment by 007revad** [comment]
> A stupid question maybe, but are you definitely running the script with the `--hdd` option?

Well spotted! 

I just noticed the -c or --check option on it's own does not check if dedupe on hdds is enabled or not.

**Comment by 007revad** [comment]
I've just released v1.4.29
- Changed to show state of "Dedupe config menu for HDDs and 2.5 inch SSDs" even if --hdd option not used.
  - Now also shows "Run the script with the --hdd option if you want it enabled".

https://github.com/007revad/Synology_enable_Deduplication/releases

**Comment by WAdama** [comment]
Hi Dave,

you're right, I started it without --hdd

Reason in your description: Enable data deduplication for HDDs **(dangerous)**

I thought tiny would be enough...

What is tiny then for?

**Comment by 007revad** [comment]
I wrote dangerous because:
- Synology must have a reason for only allowing deduplication on SSDs.
- I don't want to be responsible if people run deduplication on HDDs and something goes wrong.

There's enough people who do run deduplication on HDDs without any reported issues that I should remove that (dangerous) comment.

> What is tiny then for?

DSM can do 2 different types of deduplication:
- "btrfs data deduplication" which requires 16GB of memory or more.
- "tiny btrfs data deduplication" which requires 4GB of memory or more.

If your Synology has more than 3GB of memory but less than 16GB the script enables "tiny btrfs data deduplication".

If your Synology has 16GB or more memory the script enables "btrfs data deduplication".

What is the difference between tiny and regular deduplication? Apart from the required amount of memory I honestly don't know. I assume tiny deduplication takes longer.

I should run some tests and time them.

**Comment by MaximumFish** [comment]
I think it's worth keeping some sort of warning there to distance yourself from any issues that may arise from an unsupported configuration. Maybe instead of "dangerous", change it to something along the lines of "HDD dedupe is not supported by Synology. No known stability issues but use at your own risk".

**Comment by 007revad** [comment]
> Edit: Or just "unsupported - use at your own risk" if you want to keep it short and sweet. 😄

I had just removed (dangerous) minutes before your reply.

Then I saw your reply and changed it to "HDD data deduplication is not supported by Synology. No known stability issues but use at your own risk".

And now you've edited your reply 😄

**Comment by WAdama** [comment]
Hi Dave, 

did use --hdd and now the missing point is shown. As my DS420+ have 10GB RAM, your script enabled tiny dedup.

Just running a dedup analysis...

**Comment by dmaclip** [comment]
seeing this on DS1522+

Dedupe config menu for HDDs and 2.5" SSDs already enabled.

but nothing in menu.
usage details are enabled.
can start new post if needed.

**Comment by 007revad** [comment]
> but nothing in menu.

In which menu?

<img width="1257" height="676" alt="Image" src="https://github.com/user-attachments/assets/817f2c48-6b51-4875-816f-2ab186b55d81" />

**Comment by dmaclip** [comment]
the configure under the 3 dots.

<img width="627" height="465" alt="Image" src="https://github.com/user-attachments/assets/66211ff9-92fb-4460-8bfa-1ae616a6b337" />
