### ISSUE TITLE
Would it still work with DSM 7.2.2?

### ISSUE THREAD

**Issue by Feathered-Serpent** [007revad/Synology_enable_Deduplication#87]
Heya

I waited with using this software here until 7.2.2 came out for my Synology, which finally did:
https://update.synology.com/autoupdate/whatsnew.php?model=DS1621%2B&update_version=69057-5

I installed the version yesterday. My question is: would it be safe to use the Deduplication enabler with this version?

**Comment by 007revad** [comment]
Yes, Synology_enable_Deduplication works in DSM 7.2.2

**Comment by Feathered-Serpent** [comment]
Thank you for the confirmation.
